---

director:
  api: http://127.0.0.1:25555
  user: admin
  password: admin

intervals:
  poll_user_sync: 1

nats:
  config_file_path: /var/vcap/data/nats/auth.json
  nats_server_executable: /var/vcap/packages/nats/bin/nats-server



