---

director:
  url: http://127.0.0.1:25555
  user: admin
  password: admin
  client_id: client_id
  client_secret: client_secret
  ca_cert: ca_cert

intervals:
  poll_user_sync: 1

nats:
  config_file_path: /var/vcap/data/nats/auth.json



